import { useEffect, useMemo, useState } from 'react';
import { api, type FacilityFeature, type SectorFeature } from './api/client';
import { Filters } from './components/Filters';
import { StatusRegion } from './components/StatusRegion';
import { FacilityDetails } from './components/FacilityDetails';
import { RiskMap } from './map/RiskMap';
import { SectorTable } from './table/SectorTable';
import { FacilityList } from './table/FacilityList';

export function HealthAccessPage() {
  const params=new URLSearchParams(location.search); const [view,setView]=useState<'sus'|'total'>(params.get('view')==='total'?'total':'sus');
  const [categories,setCategories]=useState<string[]>(params.get('categories')?.split(',').filter(Boolean)??[]); const [metadata,setMetadata]=useState<any>(null);
  const [sectors,setSectors]=useState<SectorFeature[]>([]); const [facilities,setFacilities]=useState<FacilityFeature[]>([]); const [selectedSector,setSelectedSector]=useState<string|null>(null); const [facility,setFacility]=useState<any>(null); const [status,setStatus]=useState('Carregando dados territoriais…'); const [error,setError]=useState('');
  useEffect(()=>{ const controller=new AbortController(); api.metadata(controller.signal).then(setMetadata).catch(reason=>{if(reason.name!=='AbortError')setError(reason.message)}); return()=>controller.abort(); },[]);
  useEffect(()=>{ const controller=new AbortController(); setStatus('Recalculando estabelecimentos e risco para o recorte…'); Promise.all([api.facilities(view,categories.filter(Boolean),controller.signal),api.sectors(view,categories.filter(Boolean),controller.signal)]).then(([facilityCollection,sectorCollection])=>{setFacilities(facilityCollection.features);setSectors(sectorCollection.features);setStatus(`${facilityCollection.features.length} estabelecimentos e ${sectorCollection.features.length} setores recalculados para o recorte ${view==='sus'?'SUS':'total'}.`)}).catch(reason=>{if(reason.name!=='AbortError')setError(reason.message)}); const next=new URLSearchParams(); if(view==='total')next.set('view','total'); if(categories.length)next.set('categories',categories.join(',')); history.replaceState(null,'',`${location.pathname}${next.size?`?${next}`:''}`); return()=>controller.abort(); },[view,categories]);
  const selected=useMemo(()=>sectors.find(item=>item.id===selectedSector)??null,[sectors,selectedSector]);
  const openFacility=(id:string)=>{const controller=new AbortController();api.facility(id,controller.signal).then(setFacility).catch(reason=>setError(reason.message));};
  return <><a className="skip-link" href="#main">Ir para o conteúdo principal</a><header className="masthead"><div className="brand-mark" aria-hidden="true"><span></span><span></span><span></span></div><div><strong>Acesso BH</strong><span>Observatório territorial de saúde</span></div><p>Dados experimentais · Censo 2022 + CNES</p></header>
    <main id="main"><section className="intro"><div><h1>Onde o acesso à saúde encontra mais barreiras?</h1><p>Compare setores de Belo Horizonte por distância, oferta alcançável e vulnerabilidade populacional. O resultado é relativo ao recorte selecionado.</p></div><div className="method-note"><strong>Leia como sinal, não diagnóstico.</strong><span>A proxy V06006 descreve rendimento mediano da pessoa responsável; não mede pobreza ou renda per capita.</span></div></section>
      {error&&<div className="error" role="alert"><strong>Os dados não carregaram.</strong> {error}<button onClick={()=>location.reload()}>Tentar novamente</button></div>}
      <Filters view={view} categories={metadata?.categories??[]} selected={categories} onView={setView} onCategories={value=>setCategories(value.includes('')?[]:value)}/><StatusRegion message={status}/>
      <section className="workspace" aria-label="Exploração territorial"><div className="map-column"><div className="map-heading"><div><h2>Risco relativo por setor</h2><p>{view==='sus'?'Estabelecimentos ativos com atendimento SUS':'Todos os estabelecimentos ativos'}{categories.length?` · ${categories.join(', ')}`:''} · geometria sintética</p></div><ol className="legend" aria-label="Faixas de risco"><li><i className="band-1"></i>Menor</li><li><i className="band-2"></i>2</li><li><i className="band-3"></i>3</li><li><i className="band-4"></i>4</li><li><i className="band-5"></i>Maior</li></ol></div><RiskMap sectors={sectors} facilities={facilities} selected={selectedSector} onSector={setSelectedSector} onFacility={openFacility}/></div>
        <div className="analysis-column"><h2>Leitura do setor</h2>{selected?<div className="sector-reading"><div className="risk-number"><span>Faixa</span><strong>{selected.properties.riskBand??'—'}</strong><span>{selected.properties.riskBand?'de 5':'sem classificação'}</span></div><h3>Setor {selected.properties.geocode.slice(-4)}</h3><p>{selected.properties.population.toLocaleString('pt-BR')} moradores · pontuação {selected.properties.riskScore?.toLocaleString('pt-BR',{maximumFractionDigits:2})??'—'}</p><dl className="components"><div><dt>Distância a pé</dt><dd>{selected.properties.distance.walkingM?.toLocaleString('pt-BR')??'—'}{selected.properties.distance.walkingM!==null?' m':''}</dd></div><div><dt>Transporte público</dt><dd>{selected.properties.distance.transitMinutes??'—'}{selected.properties.distance.transitMinutes!==null?' min':''}</dd></div><div><dt>Oferta em 30 min</dt><dd>{selected.properties.offer.reachable30m} locais</dd></div><div><dt>Rendimento mediano</dt><dd>R$ {selected.properties.vulnerability.responsiblePersonMedianIncomeBrl.toLocaleString('pt-BR')}</dd></div></dl><p className="confidence">{selected.properties.confidence==='unclassified'?'Sem estabelecimento elegível; o setor não pode ser classificado neste recorte.':'Dados completos para as três dimensões.'}</p></div>:<div className="selection-prompt"><span aria-hidden="true">↗</span><p>Selecione um setor no mapa ou na tabela para decompor o risco.</p></div>}<FacilityList facilities={facilities} onSelect={openFacility}/></div></section>
      <section className="table-section"><div><h2>Alternativa textual ao mapa</h2><p>A mesma classificação, ordenável e operável por teclado.</p></div><SectorTable sectors={sectors} selected={selectedSector} onSelect={id=>{setSelectedSector(id);document.querySelector('.analysis-column')?.scrollIntoView({behavior:'smooth'})}}/></section>
      <footer><p><strong>{metadata?.edition.label??'Fixture sintética'}</strong> · metodologia {metadata?.methodology.version??'1.0.0'}</p><p>Fontes previstas: IBGE, CNES, OpenStreetMap e GTFS/PBH.</p></footer></main>{facility&&<FacilityDetails facility={facility} onClose={()=>setFacility(null)}/>}</>;
}
